#Requires -Version 5.1
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envLocal = Join-Path $root ".env.development.local"
$projectConfig = Join-Path $root "project.config.json"

$ip = $null
try {
  $ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.PrefixOrigin -ne "WellKnown" -and
      $_.InterfaceAlias -notmatch "Loopback|vEthernet|WSL|VMware|VirtualBox|Hyper-V" -and
      $_.IPAddress -match "^(192\.168|10\.\d+\.)"
    } |
    Sort-Object -Property InterfaceMetric |
    Select-Object -ExpandProperty IPAddress -First 1
} catch {
  # ignore
}

if (-not $ip) {
  $ip = "127.0.0.1"
  Write-Host "[warn] No LAN IPv4 found, fallback to 127.0.0.1 (simulator only)"
}

$origin = "http://${ip}:9000"
$proxy = "http://127.0.0.1:9000"

$envContent = @"
# Auto-generated by scripts/resolve-api-origin.ps1 ($(Get-Date -Format 'yyyy-MM-dd HH:mm'))
# Prefer editing project.config.json apiOrigin for WeChat MP.
VITE_COMMENTARY_DEV_PROXY_TARGET=$proxy
VITE_API_ORIGIN=$origin
"@
Set-Content -Path $envLocal -Value $envContent.TrimEnd() -Encoding UTF8

if (Test-Path $projectConfig) {
  $text = [System.IO.File]::ReadAllText($projectConfig)
  if ($text -match '"apiOrigin"\s*:') {
    $text = [regex]::Replace($text, '"apiOrigin"\s*:\s*"[^"]*"', ('"apiOrigin": "' + $origin + '"'))
  } else {
    $text = [regex]::Replace($text, '\{', "{`r`n  `"apiOrigin`": `"$origin`",", 1)
  }
  [System.IO.File]::WriteAllText($projectConfig, $text, (New-Object System.Text.UTF8Encoding $false))
  Write-Host "Updated project.config.json apiOrigin=$origin"
} else {
  Write-Host "[warn] project.config.json missing, skip"
}

Write-Host "Wrote $envLocal"
Write-Host "  VITE_API_ORIGIN=$origin"
Write-Host "  (H5 dev still uses Vite proxy to 127.0.0.1:9000)"
